### ISSUE TITLE
need new icon for builder?

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#342] opened 2016-07-14 20:45 UTC
@carlostallon since we're creating a new builder course, we probably need a nice new icon for it too :) What do you think?

**Comment by carlostallon** [comment] 2016-07-15 09:20
Of course, I will send you today : )

**Comment by carlostallon** [comment] 2016-07-15 13:49
Here it goes Andy ;)

[builder icon.zip](https://github.com/CartoDB/academy/files/366075/builder.icon.zip)

**Comment by ohasselblad** [comment] 2016-07-15 13:52
@nygeog here are your new assets for the builder lesson :)

**Comment by csobier** [comment] 2016-08-04 18:53
Duplicate of Docs icon that was already created- please let's try to use single-sourcing as often as possible :-)

**Comment by carlostallon** [comment] 2016-08-08 14:38
It's better because they are related, we used also the same icon in SQL or CARTO.js for example.

**Closed** 2016-08-23 16:34 UTC
Labels: design
