### ISSUE TITLE
Data not appearing on course intro screens

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/academy#96] opened 2014-11-18 04:08 UTC
The data layer is not loading here
http://academy.cartodb.com/courses/03-cartodbjs-ground-up.html

I don't know if it's related, but this error appears in the console log: `Uncaught ReferenceError: functionreturn_cdbc_cartodb is not defined`

The data appears normally in the lessons
http://academy.cartodb.com/courses/03-cartodbjs-ground-up/lesson-1.html

**Comment by ohasselblad** [comment] 2015-02-16 17:55
@matallo , FYI. Should've pinged you before.
Duplicate of CartoDB/cartodb.js#341

**Comment by matallo** [comment] 2015-02-16 17:56
yeah, waiting for fix on Cartodb.js, thanks! :)

**Comment by ohasselblad** [comment] 2015-03-19 16:04
@matallo any update on this?

**Comment by matallo** [comment] 2015-03-20 09:31
it still needs the fix from cartodb.js, which at the moment is not priority, but still in the backlog, sorry @ohasselblad

**Comment by ohasselblad** [comment] 2015-05-25 18:20
Any progress on this yet?

**Comment by ohasselblad** [comment] 2015-06-08 17:55
@javisantana here's the issue we discussed earlier

**Closed as completed** 2016-11-23 00:23 UTC
Labels: bug
